# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A blog about my AI and Machine Learning toy projects'
url:              
baseurl:          /

author:
  name:           'Srinath Rajagopalan'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/thegyro/thegyro.github.io
